### ISSUE TITLE
Create a navbar for landing page

### ISSUE THREAD

**Issue by abhigyank** [KamandPrompt/Faculty-Availability#4]
It would go in index.html file and have links to login and signup as well as link to an availability page (can be a dummy link now) . The navbar should also have the project name on left corner (could be a logo too if you can :P) 
** Before starting to work on it, make sure you discuss the design on Zulipchat with others. **

**Comment by Sarthakj0805** [comment]
claim issue

**Comment by abhigyank** [comment]
Closed in #5 :rocket:
